CREATE TABLE `email_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(255) NOT NULL,
  `to` TEXT NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `successful` BOOLEAN NOT NULL,
  `content` LONGTEXT NOT NULL,
  `api_error` LONGTEXT NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
