export interface ContactListItem {
  id: number,
  name:string,
  email:string,
  representative:string,
  partner:{ id: number, name: string },
  is_partner:boolean,
  orders:[],
}

export interface Contact {
  id:number,
  name:string,
  representative:string,
  email:string,
  phone:string,
  phone2:string,
  street:string,
  street_extra:string,
  city:string,
  country:string,
  state:string,
  zip:string,
  street2:string,
  street_extra2:string,
  city2:string,
  country2:string,
  state2:string,
  zip2:string,
  kvk_nr:string,
  is_partner:number,
  partner_id:number,
}
